version: "3"

services:
  node-app:
    build: .
    image: graphql-node-boilerplate
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/boilerplate
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/graphql-node-boilerplate
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
